samples:
  EV_K4me3_S1_R1_001_sample100: "EV_K4me3_S1_R1_001_sample100.fastq"
  EV_input_S7_R1_001_sample100: "EV_input_S7_R1_001_sample100.fastq"

make_BSgenome_fasta: False # if this is true, then the entry to 'fasta' wont matter, the result of this download will be used
user_fasta: "BSgenome.Hsapiens.UCSC.hg19.fa" # leave blank if making fasta internally

# only fill this in if you left fasta blank

genome: "hg19"

#aligner: "bwa"
#aligner: "bowtie2"
aligner: "Rsubread"
align_cores: 2

index: False

remove_duplicates: True
bam_mapq: 15

peak_samplesheet_path: "sample_sheet_test.csv"

extra_peaks_args: " "
